### ISSUE TITLE
Import client side modules in ssr mode

### ISSUE THREAD

**Issue by asieverding** [marko-js/vite#25]
Hey :) Is it possible to import client side modules in server side rendering mode at the top of a component?
I try to use Bootstrap for example, but I can't import the js into my marko component, because window.document don't exists on the server side. Is there a way to tell marko or vite that the component uses client side modules or should the plugin already recognize that and this is a common bug?

I work with the [vite-express example](https://github.com/marko-js/examples/tree/master/examples/vite-express) and try to [import Bootstrap](https://getbootstrap.com/docs/5.2/getting-started/vite/#import-bootstrap) components into my marko component.

```marko
import { Tooltip, Toast, Popover } from 'bootstrap'
```

I can import all of Bootstrap js into a single client js file, set the bootstrap variable as global window variable and load this file as module in my apps html head with a script tag. In this case it is working fine but this scenario won't work for all cases like the import of external marko components which are import client side code directly.

I don't know if this is the right Repo for reporting this issue or if I am on the wrong way here but I cannot find a solution for this.

**Comment by DylanPiercey** [comment]
@asieverding I think this could be improved on our end to allow client only imports. However one thing that could work for you is to leverage our [split components](https://markojs.com/docs/class-components/#split-components).

Split components aren't really meant for this use case, but they do allow you to have a `component-browser.js` file which is _only_ imported by the browser and so it'd be safe to import `bootstrap` from there.

**Comment by asieverding** [comment]
@DylanPiercey I'm glad to see that it works! Now I can use client side code in my app.
It would be cool if one could load clientside code directly into the template but as a workaround it works like this for now.
