### ISSUE TITLE
"preserve-tag" is not supported resolving ES modules

### ISSUE THREAD

**Issue by JPritchard9518** [marko-js/vite#36]
### Details

When using the `no-update` attribute on an element, our production builds break with the following error:

`Directory import '.../node_modules/marko/dist/core-tags/components/preserve-tag' is not supported resolving ES modules imported from '.../dist/index.js' Did you mean to import marko/dist/core-tags/components/preserve-tag/index.js?`

We are able to work around it by manually changing the following line in our build output from:
`import _preserve from "marko/dist/core-tags/components/preserve-tag";`
to
`import _preserve from "marko/dist/core-tags/components/preserve-tag/index.js";`

<details><summary>Additional Info</summary>

### Your Environment

Node 16.14.0
</details>

**Comment by DylanPiercey** [comment]
This is resolved in the latest version of Marko
