### ISSUE TITLE
Hot reload not working when marko file has no class declared

### ISSUE THREAD

**Issue by andresilvasantos** [marko-js/vite#49]
### Details

Let's say app-main from (https://github.com/marko-js/examples/tree/master/examples/vite-express) is a single index.marko file with the following code:

```
class {} // THIS NEEDS TO BE HERE FOR HOT RELOAD TO WORK

<div.rect />

style {
    .rect {
        background-color: red;
        height: 100px;
        width: 100px;
    }
};
```

Without the class declaration, hot reload doesn't work on that component.

### Expected Behavior

Hot reload should be happening, but the page needs to be manually reloaded for the changes to happen.
And when I manually reload, the following errors show up in the browser console:

```
TypeError: error loading dynamically imported module
[hmr] Failed to reload /src/components/app-main/index.marko. This could be due to syntax errors or importing non-existent modules.
```

Let me know if you need further info. Thank you!

**Comment by DylanPiercey** [comment]
All known HMR issues have been fixed. This appears to be working also!
